# Netlify Configuration

# Build settings
[build]
  base = "website/"
  publish = ".next"
  command = "npm run build"

# Environment variables
[build.environment]
  NODE_VERSION = "18"

# Redirects and headers
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:; connect-src 'self' https://api.openai.com https://*.azure.com https://*.googleapis.com;"

# Functions
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Plugins
[[plugins]]
  package = "@netlify/plugin-nextjs"
